name: Create Page for User Management

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Create page
      run: |
        python user_mgmt.py
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.1
      with:
        name: UserMgmt
        path: index.html
